### ISSUE TITLE
Should this go into the CLDF cookbook?

### ISSUE THREAD

**Issue by xrotwang** [bambooforest/visualizing-typology-data#1]
Seems I never responded when you told me about this. My bad. Looking at this now, I think it should go into the [CLDF cookbook](https://github.com/cldf/cookbook). It's exactly the kind of code I'd like to work with generic CLDF datasets, thereby advertising the usefulness of standard formats.

**Comment by xrotwang** [comment]
I could ask @chrzyki to port the code - unless you'd like to do it.

**Comment by bambooforest** [comment]
Sounds good. I'm OK with @chrzyki porting the code. Ideally we'd like to be able to show it along with the associated paper at LREC (7 to 12 May) this year.

**Comment by chrzyki** [comment]
Ok, will try my hand at this! Thanks for providing nice starting point like this.

**Comment by bambooforest** [comment]
Done. Thanks @chrzyki
https://github.com/cldf/cookbook/tree/master/recipes/cldf_r
